### ISSUE TITLE
APIBroker Service stops unexpectedly

### ISSUE THREAD

**Issue by prathameshd** [airavata-courses/Team-Rocket#113]
After a few requests are successful, APIBroker stops execution occasionally. Checked using netstat with port.

**Comment by aravindparappil46** [comment]
This issue has been experience with the RecoEngine as well. Not sure of its cause

**Comment by aravindparappil46** [comment]
@BBaggines @tylerthedeveloper @chetan253 @maheshbelnekar Please note that this is one of the major issues we are facing currently. We are actively working on fixing the same. 
Due to the APIBroker service shutting down unexpectedly (not sure when or why), some features will break in the current build.

**Comment by tylerthedeveloper** [comment]
Not sure if i am facing this issue but it seems to bet currently down, please let me know if this is true

**Comment by aravindparappil46** [comment]
@tylerthedeveloper Checking the same.

**Comment by aravindparappil46** [comment]
@tylerthedeveloper Yep. It seems to be out again. netstat tells me that the service is listening on that port but for some reason, requests are timing out.
I am running Jenkins Job_ZK_Clean now to do a fresh build. Please wait for a while (~2mins) for the jobs to finish executing. This might solve it

**Comment by prathameshd** [comment]
This problem has been resolved. Closing the issue.
