### ISSUE TITLE
Peer Review Milestone 2

### ISSUE THREAD

**Issue by chetan253** [airavata-courses/Team-Rocket#121]
Hi Team-Rocket,

I've gone through the documentation and it seems well structured with details and easy to figure out the flow of systems. Also, we faced the same issues while deployment using Jenkins and I know it's quite a difficult situation to deal with. 

I am interested to know that is recommendation engine using certain ML model to provide a recommendation? If so how did you managed to deploy them or are you using an API?

Can you email me the Jenkins credentials on cpatil@iu.edu

Thanks,
Chetan

**Comment by aravindparappil46** [comment]
Hi Chetan,
Thanks for being understanding! 
No, we are not using ML for recommendation. Since we are building on top of Spotify, we take the recent history of the user (last 10 songs played) and extract a feature called 'valence' from each of them. An average valence is then calculated and a list of songs matching that avg. value is shown to the user

**Comment by chetan253** [comment]
Thanks for the info @aravindparappil46 .
I've gone through the Jenkins and there were no issues while the whole process. All the services for milestone 2 are working great!! 

However, I encountered a situation while going through the web app, that if you click on Utopia logo after login there is no way to go back on my dashboard. It's just a quick fix by adding a dashboard button for logged in user you might want to look at.

-Chetan

**Comment by aravindparappil46** [comment]
Thanks for pointing it out, @chetan253 ! I have raised an issue for it as well #123
